### PR TITLE
Fix bug found from test during PE-D 

### LINKED ISSUE #279: [PE-D][Tester C] Error message for adding duplicate equipment does not provide correct instructions
When adding an equipment with duplicate name, the error message suggests appending a suffix to "basketball".

Image

However, doing so does not resolve the error.

Image

The error message could be made clearer to prevent confusion between whether "basketball" refers to a name or a category.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #280: [PE-D][Tester C] Add equipment command allows multiple name parameters to be provided
When the following input is provided:

Image

The command executes and adds the following equipment:

Image

However, users should not be allowed to provide duplicate names since only one of them is used.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #281: [PE-D][Tester C] Add equipment command allows multiple category parameters to be provided
When the following input is provided:

Image

The command executes and adds the following equipment:

Image

However, users should not be allowed to provide duplicate categories since only one of them is used.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #286: [PE-D][Tester C] Edit equipment command allows multiple name parameters to be provided
When the following input is provided:

Image

The command executes and updates the equipment to the following:

Image

However, users should not be allowed to provide duplicate names since only one of them is used.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #287: [PE-D][Tester C] Edit equipment command allows multiple category parameters to be provided
When the following input is provided:

Image

The command executes and updates the equipment to the following:

Image

However, users should not be allowed to provide duplicate categories since only one of them is used.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #288: [PE-D][Tester C] Edit equipment command allows multiple status parameters to be provided
When the following input is provided:

Image

The command executes and updates the equipment to the following:

Image

However, users should not be allowed to provide duplicate statuses since only one of them is used.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #289: [PE-D][Tester D] edit-r UG lists wrong prefix
Under the edit-r section in the User Guide, the list of possible errors has a typo in the prefixes (last bullet point):

Image

This seems to be copy-paste error from the edit-e section.

Expected: The possible errors should read: "Invalid command: Missing n/, l/, or s/ prefix."

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #290: [PE-D][Tester C] Add room command allows multiple name parameters to be provided
When the following input is provided:

Image

The command executes and adds the following room:

Image

However, users should not be allowed to provide duplicate names since only one of them is used.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #291: [PE-D][Tester C] Add room command allows multiple location parameters to be provided
When the following input is provided:

Image

The command executes and adds the following room:

Image

However, users should not be allowed to provide duplicate locations since only one of them is used.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #295: [PE-D][Tester C] Rooms with the same name in different locations should not be considered duplicates
After adding "seminar-room-1" in "com1",

Image

The app does not allow "seminar-room-1" in "rvrc" to be added.

Image

However, these two rooms should not be considered duplicates since different locations may use the same naming conventions.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #301: [PE-D][Tester D] Delete commands show different error messages for invalid indexes
When an invalid index is zero or negative, the general invalid command format error is given. However, when the index is beyond the list, it is the specific invalid index error. 

Image

This behavior differs from the UG which implies the user should be facing the same invalid index error, for all types of invalid indexes.

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #303: [PE-D][Tester C] Error message for delete room command not specific enough
The error message for an index that is outside of the list range should be an invalid input, and not an invalid format.

Image

To fix this issue, you can simply change the above error message to only specify that the index is invalid since the invalid format case is already covered by a different error message.

Image

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #306: [PE-D][Tester C] Incorrect categorisation of possible errors for delete-r section in user guide
The user guide classifies 0 and negative indices as invalid inputs.

Image

However, the app classifies them as invalid command formats.

Image
Image

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #307: [PE-D][Tester C] Edit room command allows duplicate parameters to be provided
When the following input is provided:

Image

The command executes and updates the room to the following:

Image

However, users should not be allowed to provide duplicate parameters since only one of them is used.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #312: [PE-D][Tester B] UI Cut Off Upon Opening App
Upon launching TrackMasterPro, the Graphical User Interface (GUI) does not scale or fit correctly within the window boundaries. Key UI components—specifically the Student List on the left and the Header/Command Box area—are visually cut off or truncated. This prevents the user from seeing full student details (such as names and matriculation numbers) and makes the interface appear unprofessional and broken.

Screenshots:
Image

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### LINKED ISSUE #326: [PE-D][Tester B] UG: Grammatical Issue in Quick Start
Image

There is a minor grammatical issue in User Guide Page 3 under Quick Start Section for Mac Devices. A more appropriate phrasing would be "A GUI similar to what is shown below should appear."

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #329: [PE-D][Tester B] UG: edit-r example in Quick Start section is incorrect
Image

On the Quick Start page, the example command reads:

> `edit-r 3 n/Tennis-Court` : Edits the room in the second index of room list to a name Tennis-Court.

The description says "second index" but the command uses index `3`, which is the third index. This is a factual inaccuracy that could mislead new users learning the index-based system. Description should say "third index" or the command should use index 2.

-------------
Labels: `severity.Medium` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by javnz1**
**Bug Fixed:**
- Fix the description for edit-r in Quick Start section. closes #329 
- Fix grammatical issue in Quick Start closes #326 
- Fix UI start up resolution for TrackMasterPro (changed 4 LoC in MainWindow.java and fxml) closes #312 
- Fix categorization regarding invalid index and invalid command format for possible errors under delete-r command closes #306 
- Fix error message of invalid index input for delete-r (changed 2 LoC in DeleteRoomCommand.java) closes #303 
- Fix categorization regarding invalid index and invalid command format for possible errors under delete-e command closes #301 
- Fix duplication handling for Room in User Guide to be more detailed closes  #295 
- Fix prefix typo in edit-r under possible errors section closes #289 
- Fix error message for duplicate equipment to be more clear closes #279 
- Fix Add Room to restrict multiple name parameters and location parameters (changed 1 LoC in AddRoomCommandParser.java) closes #290 closes #291 
-  Fix Edit Room to restrict multiple name parameters, location parameters and status parameters (changed 1 LoC in EditRoomCommandParser.java) closes #307 
-  Fix Edit Equipment to restrict multiple name parameters, category parameters and status parameters (changed 1 LoC in EditEquipmentCommandParser.java) closes #287 closes #286 closes #288 
- Fix Add Equipment to restrict multiple name parameters and category parameters (changed 1 LoC in AddEquipmentCommandParser.java) closes #281 closes #280 

**Total changed 10 LoC in functionality file** 

**Issue that was raised, but user guide have stated the expected behaviour:**
Issue 286 - for @LiaoYantong to follow up

### CODE REVIEW

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -148,14 +148,14 @@ void fillInnerParts() {
      * Sets the default size based on {@code guiSettings}.
      */
     private void setWindowDefaultSize(GuiSettings guiSettings) {
-        primaryStage.setMinWidth(1400);
+        primaryStage.setMinWidth(1200);
```
Comment (junxiancheh) [inline src/main/java/seedu/address/ui/MainWindow.java:151]: Good. Fixed the resolution issue.

File: src/main/java/seedu/address/logic/parser/EditRoomCommandParser.java [hunk 2]
```diff
@@ -24,6 +24,8 @@ public EditRoomCommand parse(String args) throws ParseException {
         ArgumentMultimap argMultimap =
                 ArgumentTokenizer.tokenize(args, PREFIX_NAME, PREFIX_LOCATION, PREFIX_STATUS);
 
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME, PREFIX_LOCATION, PREFIX_STATUS);
```
Comment (junxiancheh) [inline src/main/java/seedu/address/logic/parser/EditRoomCommandParser.java:27]: Good, fixed no duplicate prefixes.

File: docs/UserGuide.md [hunk 3]
```diff
@@ -906,11 +910,13 @@ Furthermore, certain edits can cause the TrackMasterPro to behave in unexpected
...
+**Workaround:** Enter the name without the special character (e.g., `Al Haddad` or `DSouza`) until a future update expands the character support. Removing special characters from the requirements allows for faster command entry and fewer parsing errors during high-pressure facility management scenarios
 
 4. **UI Refresh Latency:** The student list does not refresh in real-time when a reservation or equipment loan becomes overdue. While the system correctly identifies the status change in the database, the Graphical User Interface (GUI) may still show the old status (e.g., "Booked" instead of "Overdue").
 **Workaround:*** Simply click anywhere within the application window to force the UI to refresh and display the most current statuses.
 
+5. **Room Name Based Uniqueness:** The current iteration of the system does not support identical room names across different locations. (e.g., `add-r n/seminar-room-1 l/Com1` and following that input `add-r n/seminar-room-1 l/Rc4`) will trigger room already exists in system.
+   **Workaround:** Input `add-r n/seminar-room-1 l/Com1` for location Com1 and input `add-r n/SR1 l/Rc4` for location Rc4.
```
Comment (junxiancheh) [inline docs/UserGuide.md:919]: Good known bugs

File: docs/UserGuide.md [hunk 4]
```diff
@@ -47,19 +47,19 @@ During high-pressure periods such as the Inter-Hall Games (IHG), Inter-College G
...
+
    4. Type the command in the command box and press Enter to execute it. e.g., typing **`help`** and pressing Enter will show all the command in the result box.
-   
+
    Some example commands you can try:
 
    * `add-s n/John Doe m/A0123456B p/91234567 e/e0123456@u.nus.edu` : Adds a new student with the name `John Doe`, matric number `A0123456B`, phone number `91234567` and email address `e0123456@u.nus.edu`.
 
-   * `edit-r 3 n/Tennis-Court` : Edits the room in the second index of room list to a name `Tennis-Court`.
+   * `edit-r 3 n/Tennis-Court` : Edits the room in the third index of room list to a name `Tennis-Court`.
```
Comment (junxiancheh) [inline docs/UserGuide.md:59]: Good catch.

**Comment by OnlyTheEnd** [comment]
LGTM
