### PR TITLE
Fix HelpWindow redirect to TrackMasterPro User Guide

### LINKED ISSUE #184: Alpha-Bug: Help button redirects to default AB3

### PR DESCRIPTION
**Pull request by javnz1**
Closes #184

### CODE REVIEW

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 1]
```diff
@@ -15,7 +15,7 @@
  */
 public class HelpWindow extends UiPart<Stage> {
 
-    public static final String USERGUIDE_URL = "https://se-education.org/addressbook-level3/UserGuide.html";
+    public static final String USERGUIDE_URL = "https://ay2526s2-cs2103t-t14-4.github.io/tp/UserGuide.html";
```
Comment (junxiancheh) [inline src/main/java/seedu/address/ui/HelpWindow.java]: LGTM. Link is fixed :)
