### PR TITLE
Fix allow issue and reserve maintainance objects bug

### LINKED ISSUE #187: Alpha Bug: maintenance item can be issued to students

### PR DESCRIPTION
**Pull request by LiaoYantong**
Closes #187

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -205,13 +205,15 @@ public boolean hasReservableItem(String resourceId) {
...
-                .anyMatch(room -> room.getName().fullName.equalsIgnoreCase(resolvedResourceId));
+        boolean availableRoomExists = addressBook.getRoomList().stream()
+                .anyMatch(room -> room.getName().fullName.equalsIgnoreCase(resolvedResourceId)
+                        && room.getStatus().toString().equalsIgnoreCase("Available"));
 
-        boolean equipmentExists = addressBook.getEquipmentList().stream()
-                .anyMatch(equipment -> equipment.getName().fullName.equalsIgnoreCase(resolvedResourceId));
+        boolean availableEquipmentExists = addressBook.getEquipmentList().stream()
+                .anyMatch(equipment -> equipment.getName().fullName.equalsIgnoreCase(resolvedResourceId)
+                        && equipment.getStatus() == EquipmentStatus.AVAILABLE);
```
Comment (junxiancheh) [inline src/main/java/seedu/address/model/ModelManager.java]: Allow only available equipment to be reserved. LGTM.
