### PR TITLE
Fix AddStudentCommand bugs

### LINKED ISSUE #199: Alpha Bug: Quickstart download link does not direct to jar file

### LINKED ISSUE #200: Alpha Bug: Quickstart jar file name should be in lower case

### LINKED ISSUE #208: Alpha Bug: Add new student
1. Change `Adds a new borrower` to `Adds a new student` for clarity 

2. Change items to equipments.

3. Change facilities to room/faciltiies.

4. Should not allow them to add number in name.

### PR DESCRIPTION
**Pull request by junxiancheh**
closes #208 
closes #199 
closes #200

### CODE REVIEW

File: src/test/java/seedu/address/model/person/NameTest.java [hunk 1]
```diff
@@ -21,21 +22,30 @@ public void constructor_invalidName_throwsIllegalArgumentException() {
...
     public void isValidName() {
+        // valid name
+        assertTrue(Name.isValidName("peter jack")); // alphabets only
+        assertTrue(Name.isValidName("Capital Tan")); // with capital letters
+        assertTrue(Name.isValidName("Capital     Tan")); // with spaces in between
+        assertTrue(Name.isValidName("TAN")); // with all capital letters
+        assertTrue(Name.isValidName("A")); // single letter name
+        assertEquals("Tan", new Name("    Tan").fullName);
+        assertEquals("Capital", new Name("Capital    ").fullName);
+    }
```
Comment (javnz1) [inline src/test/java/seedu/address/model/person/NameTest.java]: Testing of valid names in various forms and case insensitivity. LGTM.
